version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
     - './server:/usr/src'
    env_file: docker.env
    ports:
     - "8000:8000"
    tty: true
    stdin_open: true
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
     - './client/my-site:/usr/src'
    ports:
     - "8080:8080"
    tty: true
    stdin_open: true
    env_file: docker.env
    depends_on:
     - server
    environment:
     - NODE_ENV=development
  
  # PostgreSQL
  db:
    container_name: db
    image: postgres:13-bullseye
    env_file: docker.env
    volumes:
      - './postgres_data:/var/lib/postgresql/data'